name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fork repository
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Set up git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Add upstream repository
      run: git remote add upstream https://github.com/folbricht/routedns.git

    - name: Fetch upstream
      run: git fetch upstream

    - name: Merge upstream changes
      run: |
        git merge upstream/master --allow-unrelated-histories || true
        git merge --abort || true
        git reset --hard upstream/master

    - name: Unstage specific files
      run: |
        git reset HEAD .github/workflows/build.yaml
        git reset HEAD .github/workflows/codeql-analysis.yml
        git reset HEAD .github/workflows/version_bump.yaml

    - name: Restore specific files
      run: |
        git restore --staged .github/workflows/build.yaml
        git restore --staged .github/workflows/codeql-analysis.yml
        git restore --staged .github/workflows/version_bump.yaml

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin master
